server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: vstu_authorization
    password: vstu_authorization
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  mail:
    username: j.vstu@yandex.by
    password: j.vstu@yandex.by
    host: smtp.yandex.com
    port: 465
    properties:
      mail:
        smtp:
          ssl.enable: true
          auth: true
  cloud:
    discovery:
      enabled: false
mail:
  confirm.path: http://localhost:${server.port}/api/uaa/account/confirm?uid=
  reset-password.path: http://localhost:4200/reset-password?uid=
token:
  signing.key: key255chars
  expire.time.hours: 9000
  email.confirm.time.hours: 1